// flow-typed signature: e5d56b0ad78f1f07d43d83fa2a8136ce
// flow-typed version: <<STUB>>/browserify-hmr_v^0.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserify-hmr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserify-hmr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserify-hmr/hmr-manager-template' {
  declare module.exports: any;
}

declare module 'browserify-hmr/inc/index' {
  declare module.exports: any;
}

declare module 'browserify-hmr/lib/has' {
  declare module.exports: any;
}

declare module 'browserify-hmr/lib/str-set' {
  declare module.exports: any;
}

declare module 'browserify-hmr/socket-server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserify-hmr/hmr-manager-template.js' {
  declare module.exports: $Exports<'browserify-hmr/hmr-manager-template'>;
}
declare module 'browserify-hmr/inc/index.js' {
  declare module.exports: $Exports<'browserify-hmr/inc/index'>;
}
declare module 'browserify-hmr/index' {
  declare module.exports: $Exports<'browserify-hmr'>;
}
declare module 'browserify-hmr/index.js' {
  declare module.exports: $Exports<'browserify-hmr'>;
}
declare module 'browserify-hmr/lib/has.js' {
  declare module.exports: $Exports<'browserify-hmr/lib/has'>;
}
declare module 'browserify-hmr/lib/str-set.js' {
  declare module.exports: $Exports<'browserify-hmr/lib/str-set'>;
}
declare module 'browserify-hmr/socket-server.js' {
  declare module.exports: $Exports<'browserify-hmr/socket-server'>;
}
