// flow-typed signature: fbcb2fd212e3dc5c2b7bd56167687cbb
// flow-typed version: <<STUB>>/console-polyfill_v^0.2.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'console-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'console-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'console-polyfill/index' {
  declare module.exports: $Exports<'console-polyfill'>;
}
declare module 'console-polyfill/index.js' {
  declare module.exports: $Exports<'console-polyfill'>;
}
