// flow-typed signature: 7b08296bbfba4827cda26a8462f887cb
// flow-typed version: <<STUB>>/envify_v^4.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'envify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'envify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'envify/custom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'envify/custom.js' {
  declare module.exports: $Exports<'envify/custom'>;
}
declare module 'envify/index' {
  declare module.exports: $Exports<'envify'>;
}
declare module 'envify/index.js' {
  declare module.exports: $Exports<'envify'>;
}
