// flow-typed signature: 554bc33ba41136696709c5ceea8e3e88
// flow-typed version: <<STUB>>/gulp-streamify_v^1.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-streamify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-streamify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-streamify/src/index' {
  declare module.exports: any;
}

declare module 'gulp-streamify/tests/index.mocha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-streamify/src/index.js' {
  declare module.exports: $Exports<'gulp-streamify/src/index'>;
}
declare module 'gulp-streamify/tests/index.mocha.js' {
  declare module.exports: $Exports<'gulp-streamify/tests/index.mocha'>;
}
