// flow-typed signature: e804112304a7cd4f334af1e926df1c54
// flow-typed version: <<STUB>>/ric-shim_v^1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ric-shim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ric-shim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ric-shim/index' {
  declare module.exports: $Exports<'ric-shim'>;
}
declare module 'ric-shim/index.js' {
  declare module.exports: $Exports<'ric-shim'>;
}
