// flow-typed signature: a880911e9e4b142d049ffa04115936de
// flow-typed version: <<STUB>>/rsvp_v^3.2.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rsvp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rsvp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rsvp/dist/rsvp' {
  declare module.exports: any;
}

declare module 'rsvp/dist/rsvp.min' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/-internal' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/all-settled' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/all' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/asap' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/config' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/defer' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/enumerator' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/events' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/filter' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/hash-settled' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/hash' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/instrument' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/map' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/node' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/platform' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/promise-hash' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/promise' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/promise/all' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/promise/race' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/promise/reject' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/promise/resolve' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/race' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/reject' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/resolve' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/rethrow' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/then' {
  declare module.exports: any;
}

declare module 'rsvp/lib/rsvp/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rsvp/dist/rsvp.js' {
  declare module.exports: $Exports<'rsvp/dist/rsvp'>;
}
declare module 'rsvp/dist/rsvp.min.js' {
  declare module.exports: $Exports<'rsvp/dist/rsvp.min'>;
}
declare module 'rsvp/lib/rsvp.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp'>;
}
declare module 'rsvp/lib/rsvp/-internal.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/-internal'>;
}
declare module 'rsvp/lib/rsvp/all-settled.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/all-settled'>;
}
declare module 'rsvp/lib/rsvp/all.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/all'>;
}
declare module 'rsvp/lib/rsvp/asap.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/asap'>;
}
declare module 'rsvp/lib/rsvp/config.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/config'>;
}
declare module 'rsvp/lib/rsvp/defer.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/defer'>;
}
declare module 'rsvp/lib/rsvp/enumerator.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/enumerator'>;
}
declare module 'rsvp/lib/rsvp/events.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/events'>;
}
declare module 'rsvp/lib/rsvp/filter.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/filter'>;
}
declare module 'rsvp/lib/rsvp/hash-settled.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/hash-settled'>;
}
declare module 'rsvp/lib/rsvp/hash.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/hash'>;
}
declare module 'rsvp/lib/rsvp/instrument.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/instrument'>;
}
declare module 'rsvp/lib/rsvp/map.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/map'>;
}
declare module 'rsvp/lib/rsvp/node.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/node'>;
}
declare module 'rsvp/lib/rsvp/platform.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/platform'>;
}
declare module 'rsvp/lib/rsvp/promise-hash.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/promise-hash'>;
}
declare module 'rsvp/lib/rsvp/promise.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/promise'>;
}
declare module 'rsvp/lib/rsvp/promise/all.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/promise/all'>;
}
declare module 'rsvp/lib/rsvp/promise/race.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/promise/race'>;
}
declare module 'rsvp/lib/rsvp/promise/reject.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/promise/reject'>;
}
declare module 'rsvp/lib/rsvp/promise/resolve.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/promise/resolve'>;
}
declare module 'rsvp/lib/rsvp/race.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/race'>;
}
declare module 'rsvp/lib/rsvp/reject.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/reject'>;
}
declare module 'rsvp/lib/rsvp/resolve.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/resolve'>;
}
declare module 'rsvp/lib/rsvp/rethrow.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/rethrow'>;
}
declare module 'rsvp/lib/rsvp/then.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/then'>;
}
declare module 'rsvp/lib/rsvp/utils.js' {
  declare module.exports: $Exports<'rsvp/lib/rsvp/utils'>;
}
