// flow-typed signature: 67564b4754e8da1ac039c7863d789dea
// flow-typed version: <<STUB>>/stdio_v^0.2.7/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stdio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stdio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stdio/lib/getopt' {
  declare module.exports: any;
}

declare module 'stdio/lib/progress' {
  declare module.exports: any;
}

declare module 'stdio/lib/question' {
  declare module.exports: any;
}

declare module 'stdio/lib/reading' {
  declare module.exports: any;
}

declare module 'stdio/lib/util' {
  declare module.exports: any;
}

declare module 'stdio/main' {
  declare module.exports: any;
}

declare module 'stdio/tests/00-stupid' {
  declare module.exports: any;
}

declare module 'stdio/tests/01-command-line-arguments' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stdio/lib/getopt.js' {
  declare module.exports: $Exports<'stdio/lib/getopt'>;
}
declare module 'stdio/lib/progress.js' {
  declare module.exports: $Exports<'stdio/lib/progress'>;
}
declare module 'stdio/lib/question.js' {
  declare module.exports: $Exports<'stdio/lib/question'>;
}
declare module 'stdio/lib/reading.js' {
  declare module.exports: $Exports<'stdio/lib/reading'>;
}
declare module 'stdio/lib/util.js' {
  declare module.exports: $Exports<'stdio/lib/util'>;
}
declare module 'stdio/main.js' {
  declare module.exports: $Exports<'stdio/main'>;
}
declare module 'stdio/tests/00-stupid.js' {
  declare module.exports: $Exports<'stdio/tests/00-stupid'>;
}
declare module 'stdio/tests/01-command-line-arguments.js' {
  declare module.exports: $Exports<'stdio/tests/01-command-line-arguments'>;
}
