// flow-typed signature: a557159019d1f6f4ce442fd325e76cea
// flow-typed version: <<STUB>>/webstorage-polyfill_v^1.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webstorage-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webstorage-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webstorage-polyfill/index' {
  declare module.exports: $Exports<'webstorage-polyfill'>;
}
declare module 'webstorage-polyfill/index.js' {
  declare module.exports: $Exports<'webstorage-polyfill'>;
}
